dist: bionic
language: rust
rust: 
  - nightly

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install -y build-essential g++-8 gcc-8 git libboost-all-dev libssl1.0-dev cmake

rust: nightly
 
script:
  - cargo check
    
